apiVersion: v1
kind: Pod
metadata:
  name: apace-pod1
  labels:
    team: integrations
    app: todo
spec:
  containers:
    - name: apace-container
      image: httpd:latest
      ports:
        - containerPort: 80
